CREATE TABLE sync_log (
    log_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_name   VARCHAR2(100) NOT NULL,
    record_id     NUMBER NOT NULL,
    status        VARCHAR2(20) NOT NULL,       -- SENDING, SUCCESS, ERROR
    message       VARCHAR2(4000),              -- Resposta ou erro
    log_datetime  TIMESTAMP DEFAULT SYSTIMESTAMP, -- Data + hora do log
    payload       CLOB                           -- JSON completo enviado
);

CREATE INDEX idx_sync_log_entity_status ON sync_log(entity_name, status);
COMMIT;