CREATE TABLE APP_SCRIPTS (
    ID NUMBER NOT NULL,
    SCRIPT VARCHAR2(255) NOT NULL,
    DATA_EXECUCAO TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_APP_SCRIPTS_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE NONEDITIONABLE TRIGGER TBI_APP_SCRIPTS_ID
BEFORE INSERT ON APP_SCRIPTS
FOR EACH ROW
DECLARE
    v_max_id NUMBER;
    v_curr_val NUMBER;
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_APP_SCRIPTS_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
    ELSE
        SELECT NVL(MAX(ID), 0) INTO v_max_id FROM APP_SCRIPTS;
        IF :NEW.ID > v_max_id THEN
            SELECT (SEQ_APP_SCRIPTS_ID.NEXTVAL - 1) INTO v_curr_val FROM DUAL;
            WHILE v_curr_val < :NEW.ID LOOP
                SELECT SEQ_APP_SCRIPTS_ID.NEXTVAL INTO v_curr_val FROM DUAL;
            END LOOP;
        END IF;
    END IF;
END;

INSERT INTO APP_SCRIPTS (SCRIPT) VALUES('2024_08_16_01_APP_SCRIPTS');
